name: Run tests

on:
  push:
    branches: [develop, master]
  workflow_dispatch:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
  # By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened.
  pull_request:

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    env:
      CI: true
      TZ: America/New_York
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 10
          - 12
          - 14
        architecture:
          - x64

    name: Node ${{ matrix.node_version }}
    steps:
      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Run tests
        run: |
          find ${{github.workspace}}/sample-datasets -maxdepth 1 -type f -exec yarn dataproofer {} \;
